### ISSUE TITLE
Run failed: ZZUjksb - master (1fa4aa5) 这个怎么解决 每一步都是按照readme来的

### ISSUE THREAD

**Issue by violinlwh** [codeM78/zzu_jksb-daily#1]
Run python jksb.py
Traceback (most recent call last):
  File "jksb.py", line 330, in <module>
    mail(msg, MAIL_TO)
  File "jksb.py", line 321, in mail
    send.login(MAIL_USER, MAIL_PWD)
  File "/opt/hostedtoolcache/Python/3.7.[12](https://github.com/violinlwh/zzu_jksb-daily/runs/6040811918?check_suite_focus=true#step:5:12)/x64/lib/python3.7/smtplib.py", line 726, in login
    initial_response_ok=initial_response_ok)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/smtplib.py", line 636, in auth
    (code, resp) = self.docmd("AUTH", mechanism + " " + response)
TypeError: can only concatenate str (not "bytes") to str
Error: Process completed with exit code 1.

**Comment by codeM78** [comment]
这个检查一下是不是邮箱账户名和授权码输入错误了，那个MAIL_PWD是你qq邮箱的授权码，而不是你自己的秘密。检查一下吧
