### ISSUE TITLE
urllib3.exceptions.LocationParseError: Failed to parse: []

### ISSUE THREAD

**Issue by miaozhenchao** [codeM78/zzu_jksb-daily#12]
![image](https://user-images.githubusercontent.com/64900491/204520272-fde0ecbe-650f-4cb9-b9d7-80281d93a926.png)
稍微报了个错 运行报错如上图 请问下您所用的python版本 我这里之前用的是3.6.8报错了之后 换到了3.10.8 还是报同样的错误，又换到了3.8.15 还是这个错误
详细代码如下
root@3425e8181eac:/usr/src/zzu_jksb# python -V
Python 3.8.15
root@3425e8181eac:/usr/src/zzu_jksb# python main.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 434, in prepare_url
    scheme, auth, host, port, path, query, fragment = parse_url(url)
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/url.py", line 397, in parse_url
    return six.raise_from(LocationParseError(source_url), None)
  File "<string>", line 3, in raise_from
urllib3.exceptions.LocationParseError: Failed to parse: []

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 28, in <module>
    msg = daka.sign_in(id=id, pwd=pwd, name=str(id), check_today=0)
  File "/usr/src/zzu_jksb/daka.py", line 239, in sign_in
    utils.imgurl2pic(imgurl=imgurl, dest=dest)
  File "/usr/src/zzu_jksb/utils.py", line 69, in imgurl2pic
    res = s.get(imgurl)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 436, in prepare_url
    raise InvalidURL(*e.args)
requests.exceptions.InvalidURL: Failed to parse: []

**Comment by codeM78** [comment]
你把验证码那段代码注释掉就行，参看现在的daka.py（已经注释了）就可以了。因为没有验证码的时候是获取不到图片url地址的，你要是想用的话，增加一下异常处理就行。

**Comment by miaozhenchao** [comment]
收到 麻烦您了
